# Generated by Django 2.2.4 on 2019-08-24 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('city_api_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('temperature', models.SmallIntegerField(default=0)),
                ('clouds', models.SmallIntegerField(choices=[(1, 'clear'), (2, 'partly cloudy'), (3, 'cloudy')], default=1)),
                ('subscribed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
